"""empty message

Revision ID: 10b3431d76d3
Revises: 44fa8859a3cb
Create Date: 2015-07-11 22:54:45.527749

"""

# revision identifiers, used by Alembic.
revision = '10b3431d76d3'
down_revision = '44fa8859a3cb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Token', 'test_syll')
    op.drop_column('Token', 'rules')
    op.drop_column('Token', 'alt_syll1')
    op.drop_column('Token', 'syll')
    op.drop_column('Token', 'alt_syll3')
    op.drop_column('Token', 'alt_syll2')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Token', sa.Column('alt_syll2', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('Token', sa.Column('alt_syll3', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('Token', sa.Column('syll', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('Token', sa.Column('alt_syll1', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('Token', sa.Column('rules', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('Token', sa.Column('test_syll', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    ### end Alembic commands ###
