"""empty message

Revision ID: 1cc7d716cf87
Revises: 29f6b0d43b97
Create Date: 2015-08-20 17:17:56.388656

"""

# revision identifiers, used by Alembic.
revision = '1cc7d716cf87'
down_revision = '29f6b0d43b97'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Poem', sa.Column('portion', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Poem', 'portion')
    ### end Alembic commands ###
