"""empty message

Revision ID: 1cc95617ed82
Revises: 10b3431d76d3
Create Date: 2015-07-13 10:47:05.658799

"""

# revision identifiers, used by Alembic.
revision = '1cc95617ed82'
down_revision = '10b3431d76d3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Token', sa.Column('verified', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Token', 'verified')
    ### end Alembic commands ###
