"""empty message

Revision ID: 1e6247037199
Revises: 58f378b7c6f1
Create Date: 2016-11-16 09:11:04.215989

"""

# revision identifiers, used by Alembic.
revision = '1e6247037199'
down_revision = '58f378b7c6f1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('with_loanwords', sa.Boolean(), nullable=True),
    sa.Column('p', sa.Float(), nullable=True),
    sa.Column('r', sa.Float(), nullable=True),
    sa.Column('f1', sa.Float(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Integer(), nullable=True),
    sa.Column('correct', sa.Integer(), nullable=True),
    sa.Column('simp_verified', sa.Integer(), nullable=True),
    sa.Column('simp_correct', sa.Integer(), nullable=True),
    sa.Column('comp_verified', sa.Integer(), nullable=True),
    sa.Column('comp_correct', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'Token', 'is_test_compound')
    op.drop_column(u'Token', 'is_nondelimited_compound')
    op.drop_column(u'Token', 'base')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'Token', sa.Column('base', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column(u'Token', sa.Column('is_nondelimited_compound', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column(u'Token', sa.Column('is_test_compound', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_table('Performance')
    ### end Alembic commands ###
