"""empty message

Revision ID: 203b3b587af2
Revises: 26d609554826
Create Date: 2015-11-13 21:49:29.648431

"""

# revision identifiers, used by Alembic.
revision = '203b3b587af2'
down_revision = '26d609554826'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Token', sa.Column('data', sa.Enum('train', 'dev', 'test', name='DATA'), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Token', 'data')
    ### end Alembic commands ###
