"""empty message

Revision ID: 22166ba13dbf
Revises: 4b5ef81f5ef7
Create Date: 2015-09-04 16:01:39.952802

"""

# revision identifiers, used by Alembic.
revision = '22166ba13dbf'
down_revision = '4b5ef81f5ef7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Linguist', sa.Column('is_admin', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Linguist', 'is_admin')
    ### end Alembic commands ###
