"""empty message

Revision ID: 22810ed42926
Revises: 2140108af7c2
Create Date: 2015-07-11 22:04:57.667383

"""

# revision identifiers, used by Alembic.
revision = '22810ed42926'
down_revision = '2140108af7c2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Token', sa.Column('is_foreign', sa.Boolean(), nullable=True))
    op.add_column('Token', sa.Column('rules1', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('rules2', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('rules3', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('rules4', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('syll1', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('syll2', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('syll3', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('syll4', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('test_syll1', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('test_syll2', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('test_syll3', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('test_syll4', sa.String(length=80, convert_unicode=True), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Token', 'test_syll4')
    op.drop_column('Token', 'test_syll3')
    op.drop_column('Token', 'test_syll2')
    op.drop_column('Token', 'test_syll1')
    op.drop_column('Token', 'syll4')
    op.drop_column('Token', 'syll3')
    op.drop_column('Token', 'syll2')
    op.drop_column('Token', 'syll1')
    op.drop_column('Token', 'rules4')
    op.drop_column('Token', 'rules3')
    op.drop_column('Token', 'rules2')
    op.drop_column('Token', 'rules1')
    op.drop_column('Token', 'is_foreign')
    ### end Alembic commands ###
