"""empty message

Revision ID: 26d609554826
Revises: 29a43f816461
Create Date: 2015-10-16 14:00:31.125892

"""

# revision identifiers, used by Alembic.
revision = '26d609554826'
down_revision = '29a43f816461'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Token', sa.Column('context', sa.Text(), nullable=True))
    op.add_column('Token', sa.Column('needs_context', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Token', 'needs_context')
    op.drop_column('Token', 'context')
    ### end Alembic commands ###
