"""empty message

Revision ID: 29a43f816461
Revises: 4b5ef81f5ef7
Create Date: 2015-09-07 19:47:37.596925

"""

# revision identifiers, used by Alembic.
revision = '29a43f816461'
down_revision = '4b5ef81f5ef7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Linguist', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('Token', sa.Column('gold_base', sa.String(length=80, convert_unicode=True), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Linguist', 'is_admin')
    op.drop_column('Token', 'gold_base')
    ### end Alembic commands ###
