"""empty message

Revision ID: 134b459dd021
Revises: 29f6b0d43b97
Create Date: 2015-08-10 09:20:56.945436

"""

# revision identifiers, used by Alembic.
# revision = '134b459dd021'
# revision = '35775c59d61b'
revision = '29f6b0d43b97'
# down_revision = '29f6b0d43b97'
down_revision = '134b459dd021'


from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Variation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=True),
    sa.Column('poem_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poem_id'], ['Poem.id'], ),
    sa.ForeignKeyConstraint(['token_id'], ['Token.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'Sequence', sa.Column('variation_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'Sequence_token_id_fkey', 'Sequence', type_='foreignkey')
    op.drop_constraint(u'Sequence_poem_id_fkey', 'Sequence', type_='foreignkey')
    op.create_foreign_key(None, 'Sequence', 'Variation', ['variation_id'], ['id'])
    op.drop_column(u'Sequence', 'poem_id')
    op.drop_column(u'Sequence', 'token_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'Sequence', sa.Column('token_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(u'Sequence', sa.Column('poem_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Sequence', type_='foreignkey')
    op.create_foreign_key(u'Sequence_poem_id_fkey', 'Sequence', 'Poem', ['poem_id'], ['id'])
    op.create_foreign_key(u'Sequence_token_id_fkey', 'Sequence', 'Token', ['token_id'], ['id'])
    op.drop_column(u'Sequence', 'variation_id')
    op.drop_table('Variation')
    ### end Alembic commands ###
