"""empty message

Revision ID: 3330f1dd5075
Revises: 1cc95617ed82
Create Date: 2015-07-17 17:57:01.438328

"""

# revision identifiers, used by Alembic.
revision = '3330f1dd5075'
down_revision = '1cc95617ed82'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Token', sa.Column('is_nondelimited_compound', sa.Boolean(), nullable=True))
    op.add_column('Token', sa.Column('is_test_compound', sa.Boolean(), nullable=True))
    op.add_column('Token', sa.Column('verified_again', sa.Boolean(), nullable=True))
    op.drop_column('Token', 'is_foreign')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Token', sa.Column('is_foreign', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('Token', 'verified_again')
    op.drop_column('Token', 'is_test_compound')
    op.drop_column('Token', 'is_nondelimited_compound')
    ### end Alembic commands ###
