"""empty message

Revision ID: 38843212685d
Revises: 4ebb214a8884
Create Date: 2015-08-08 18:07:10.998532

"""

# revision identifiers, used by Alembic.
revision = '38843212685d'
down_revision = '4ebb214a8884'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Token', sa.Column('rules10', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('rules11', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('rules12', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('rules13', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('rules14', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('rules15', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('rules16', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('rules9', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('syll10', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('syll11', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('syll12', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('syll13', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('syll14', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('syll15', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('syll16', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('syll9', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('test_syll10', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('test_syll11', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('test_syll12', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('test_syll13', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('test_syll14', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('test_syll15', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('test_syll16', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('test_syll9', sa.String(length=80, convert_unicode=True), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Token', 'test_syll9')
    op.drop_column('Token', 'test_syll16')
    op.drop_column('Token', 'test_syll15')
    op.drop_column('Token', 'test_syll14')
    op.drop_column('Token', 'test_syll13')
    op.drop_column('Token', 'test_syll12')
    op.drop_column('Token', 'test_syll11')
    op.drop_column('Token', 'test_syll10')
    op.drop_column('Token', 'syll9')
    op.drop_column('Token', 'syll16')
    op.drop_column('Token', 'syll15')
    op.drop_column('Token', 'syll14')
    op.drop_column('Token', 'syll13')
    op.drop_column('Token', 'syll12')
    op.drop_column('Token', 'syll11')
    op.drop_column('Token', 'syll10')
    op.drop_column('Token', 'rules9')
    op.drop_column('Token', 'rules16')
    op.drop_column('Token', 'rules15')
    op.drop_column('Token', 'rules14')
    op.drop_column('Token', 'rules13')
    op.drop_column('Token', 'rules12')
    op.drop_column('Token', 'rules11')
    op.drop_column('Token', 'rules10')
    ### end Alembic commands ###
