"""empty message

Revision ID: 38a18f8ed053
Revises: 1e6247037199
Create Date: 2016-12-05 21:08:45.146276

"""

# revision identifiers, used by Alembic.
revision = '38a18f8ed053'
down_revision = '1e6247037199'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Poet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surname', sa.Enum(u'Erkko', u'Hellaakoski', u'Kaatra', u'Kailas', u'Koskenniemi', u'Kramsu', u'Leino', u'L\xf6nnrot', u'Siljo', u'Homeros', name='surname'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('surname')
    )
    op.create_table('Book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80, convert_unicode=True), nullable=True),
    sa.Column('poet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poet_id'], ['Poet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('section', sa.Integer(), nullable=True),
    sa.Column('text', sa.PickleType(), nullable=True),
    sa.Column('status', sa.Enum(u'in-progress', u'complete', name='status'), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['Book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['Section.id'], ),
    sa.ForeignKeyConstraint(['token_id'], ['Token.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('VV',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poet_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('sequence', sa.String(length=10, convert_unicode=True), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('line', sa.String(length=140, convert_unicode=True), nullable=True),
    sa.Column('html', sa.String(length=80, convert_unicode=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('is_heavy', sa.Boolean(), nullable=True),
    sa.Column('is_stressed', sa.Boolean(), nullable=True),
    sa.Column('split', sa.Enum('split', 'join', 'unknown', name='split'), nullable=True),
    sa.Column('scansion', sa.Enum('S', 'W', 'SW', 'WS', 'SS', 'WW', 'unknown', name='scansion'), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['Book.id'], ),
    sa.ForeignKeyConstraint(['poet_id'], ['Poet.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['Variant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Sequence')
    op.drop_table('Variation')
    op.drop_table('Poem')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Variation',
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u'nextval(\'"Variation_id_seq"\'::regclass)'), nullable=False),
    sa.Column('token_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('poem_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['poem_id'], [u'Poem.id'], name=u'Variation_poem_id_fkey'),
    sa.ForeignKeyConstraint(['token_id'], [u'Token.id'], name=u'Variation_token_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'Variation_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Sequence',
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u'nextval(\'"Sequence_id_seq"\'::regclass)'), nullable=False),
    sa.Column('variation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sequence', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('html', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('split', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('scansion', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('is_odd', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['variation_id'], [u'Variation.id'], name=u'Sequence_variation_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'Sequence_pkey')
    )
    op.create_table('Poem',
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u'nextval(\'"Poem_id_seq"\'::regclass)'), nullable=False),
    sa.Column('title', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('poet', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('portion', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ebook_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_released', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('tokenized_poem', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('reviewed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('sequence_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('review_begun', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'Poem_pkey')
    )
    op.drop_table('VV')
    op.drop_table('Variant')
    op.drop_table('Section')
    op.drop_table('Book')
    op.drop_table('Poet')
    ### end Alembic commands ###
