"""empty message

Revision ID: 423081911c8e
Revises: 203b3b587af2
Create Date: 2016-01-06 22:01:30.190004

"""

# revision identifiers, used by Alembic.
revision = '423081911c8e'
down_revision = '203b3b587af2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Poem', sa.Column('review_begun', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Poem', 'review_begun')
    ### end Alembic commands ###
