"""empty message

Revision ID: 44fa8859a3cb
Revises: 22810ed42926
Create Date: 2015-07-11 22:10:14.167061

"""

# revision identifiers, used by Alembic.
revision = '44fa8859a3cb'
down_revision = '22810ed42926'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Token', sa.Column('note', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Token', 'note')
    ### end Alembic commands ###
