"""empty message

Revision ID: 4860f9f97654
Revises: 38a18f8ed053
Create Date: 2017-03-28 14:47:20.946787

"""

# revision identifiers, used by Alembic.
revision = '4860f9f97654'
down_revision = '38a18f8ed053'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Token', sa.Column('_gold_base', sa.String(length=80, convert_unicode=True), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Token', '_gold_base')
    ### end Alembic commands ###
