"""empty message

Revision ID: 4b5ef81f5ef7
Revises: 5749cc93e4d1
Create Date: 2015-08-28 11:38:16.873512

"""

# revision identifiers, used by Alembic.
revision = '4b5ef81f5ef7'
down_revision = '5749cc93e4d1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Token', sa.Column('is_complex', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Token', 'is_complex')
    ### end Alembic commands ###
