"""empty message

Revision ID: 4ebb214a8884
Revises: d30516616cd
Create Date: 2015-08-01 14:25:17.726809

"""

# revision identifiers, used by Alembic.
revision = '4ebb214a8884'
down_revision = 'd30516616cd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Token', sa.Column('base', sa.String(length=80, convert_unicode=True), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Token', 'base')
    ### end Alembic commands ###
