"""empty message

Revision ID: 58f378b7c6f1
Revises: 33193052f21
Create Date: 2016-05-08 09:26:36.139278

"""

# revision identifiers, used by Alembic.
revision = '58f378b7c6f1'
down_revision = '33193052f21'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Token', sa.Column('test_base', sa.String(length=80, convert_unicode=True), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Token', 'test_base')
    ### end Alembic commands ###
