"""empty message

Revision ID: d30516616cd
Revises: 3330f1dd5075
Create Date: 2015-07-30 09:42:16.978654

"""

# revision identifiers, used by Alembic.
revision = 'd30516616cd'
down_revision = '3330f1dd5075'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Token', sa.Column('syll5', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('syll6', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('syll7', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('syll8', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('test_syll5', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('test_syll6', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('test_syll7', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('test_syll8', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('rules5', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('rules6', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('rules7', sa.String(length=80, convert_unicode=True), nullable=True))
    op.add_column('Token', sa.Column('rules8', sa.String(length=80, convert_unicode=True), nullable=True))
    op.drop_column('Token', 'verified_again')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Token', sa.Column('verified_again', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('Token', 'test_syll8')
    op.drop_column('Token', 'test_syll7')
    op.drop_column('Token', 'test_syll6')
    op.drop_column('Token', 'test_syll5')
    op.drop_column('Token', 'syll8')
    op.drop_column('Token', 'syll7')
    op.drop_column('Token', 'syll6')
    op.drop_column('Token', 'syll5')
    op.drop_column('Token', 'rules8')
    op.drop_column('Token', 'rules7')
    op.drop_column('Token', 'rules6')
    op.drop_column('Token', 'rules5')
    ### end Alembic commands ###
